using System;

namespace SmartDisplayPcAgent.Models;

public sealed record DeviceStatusSnapshot(
    string Name,
    string Mode,
    string Ip,
    string Ssid,
    int? Rssi,
    string Theme,
    double Cpu,
    double Ram,
    double Gpu,
    double Disk,
    string DiskLabel,
    bool PcOnline,
    long? LastPcMetricsAgeMs,
    long? UptimeMs,
    string ResetReason,
    string ResetInfo,
    string RestartIntent,
    string LastCheckpoint,
    double? Temperature,
    string Weather,
    string WeatherStatus,
    long? Heap,
    int? HeapFragmentation,
    long? MaxFreeBlockSize,
    long? FlashSize,
    bool AnimationImage,
    long? AnimationImageMaxBytes,
    long? AnimationImageStorageBytes,
    bool LowHeap)
{
    public static DeviceStatusSnapshot Empty { get; } = new(
        Name: "TinyDash",
        Mode: "--",
        Ip: "--",
        Ssid: "--",
        Rssi: null,
        Theme: "pc_monitor",
        Cpu: 0,
        Ram: 0,
        Gpu: 0,
        Disk: 0,
        DiskLabel: "---",
        PcOnline: false,
        LastPcMetricsAgeMs: null,
        UptimeMs: null,
        ResetReason: "--",
        ResetInfo: "--",
        RestartIntent: "--",
        LastCheckpoint: "--",
        Temperature: null,
        Weather: "--",
        WeatherStatus: "--",
        Heap: null,
        HeapFragmentation: null,
        MaxFreeBlockSize: null,
        FlashSize: null,
        AnimationImage: false,
        AnimationImageMaxBytes: null,
        AnimationImageStorageBytes: null,
        LowHeap: false);
}
