#pragma once

#include <Arduino.h>

const char WIFI_SETUP_HTML[] PROGMEM = R"rawliteral(
<!DOCTYPE html><html><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Wi-Fi Setup</title><style>body{font-family:Arial,sans-serif;background:#111;color:#eee;margin:0;padding:20px}.card{background:#1f1f1f;padding:20px;border-radius:14px;max-width:460px;margin:auto}h2{color:#ff9800;text-align:center;letter-spacing:1px}.net{padding:12px;margin:7px 0;background:#2b2b2b;border-radius:8px;cursor:pointer}.net:hover{background:#3a3a3a}input,button,a{width:100%;padding:13px;margin:8px 0;border:none;border-radius:8px;box-sizing:border-box;font-size:16px}input{background:#2b2b2b;color:#eee}button{background:#ff9800;color:#111;font-weight:bold;cursor:pointer}a{display:block;text-align:center;text-decoration:none;background:#327df6;color:#fff;font-weight:bold}.danger{background:#a83232}.msg{text-align:center;color:#aaa}.small{text-align:center;color:#aaa;font-size:13px}</style></head><body><div class='card'><h2>Wi-Fi Setup</h2><p class='small'>Selecione uma rede ou digite manualmente.</p><div id='nets'>%NETWORKS%</div><form action='/connect' method='POST'><input id='s' name='ssid' placeholder='Nome da rede Wi-Fi' required><input name='pass' type='password' placeholder='Senha da rede'><button type='submit'>Salvar e conectar</button></form><button onclick="location.href='/scan'">Buscar redes novamente</button><a href='/update'>Firmware Update OTA</a></div><script>function sel(s){document.getElementById('s').value = s;}</script></body></html>
)rawliteral";

const char HOME_HTML[] PROGMEM = R"rawliteral(
<!DOCTYPE html><html><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>PC Monitor</title><style>body{font-family:Arial,sans-serif;background:#111;color:#eee;margin:0;padding:20px}.card{background:#1f1f1f;padding:22px;border-radius:14px;max-width:460px;margin:auto}h1{color:#ff9800;text-align:center}.info{background:#2b2b2b;padding:12px;border-radius:8px;margin:10px 0}a{display:block;width:100%;padding:14px;margin-top:12px;border-radius:8px;box-sizing:border-box;text-align:center;text-decoration:none;font-weight:bold}.ota{background:#327df6;color:#fff}.danger{background:#a83232;color:#fff}.small{text-align:center;color:#aaa;font-size:13px}</style></head><body><div class='card'><h1>PC Monitor</h1><p class='small'>ESP12F + ST7789 com Wi-Fi, OTA, hora real e clima real.</p><div class='info'><b>IP:</b> %IP%</div><div class='info'><b>SSID:</b> %SSID%</div><div class='info'><b>RSSI:</b> %RSSI% dBm</div><div class='info'><b>CPU fake:</b> %CPU%%</div><div class='info'><b>RAM fake:</b> %RAM%%</div><div class='info'><b>GPU fake:</b> %GPU%%</div><div class='info'><b>Temperatura:</b> %TEMP%</div><div class='info'><b>Heap livre:</b> %HEAP% bytes</div><a class='ota' href='/update'>Firmware Update OTA</a><a class='danger' href='/reset-wifi'>Apagar Wi-Fi salvo</a></div></body></html>
)rawliteral";
